language: ruby
services:
  - rabbitmq
notifications:
  email: true
rvm:
  - "1.9.3"
before_script:
  - rake db:migrate db:seed db:test:prepare
# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rake db:migrate db:seed db:test:prepare ci
