language: ruby
bundler_args: --without debug
services:
  - rabbitmq
notifications:
  email: true
rvm:
  - "1.9.3"
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler --pre
  - ./script/fits_install.sh
install:
  - travis_retry bundle install --deployment --without debug
  - bundle exec rake jetty:clean
  - wget https://github.com/projecthydra/hydra-jetty/raw/master/start.ini -O jetty/start.ini
  - bundle exec rake hydra:jetty:config
  - sleep 5
before_script:
  - bundle exec rake db:migrate db:seed db:test:prepare
  - bundle exec rake jetty:start
after_script:
  - bundle exec rake jetty:stop
gemfile:
  - gemfiles/Gemfile.travis
env:
  - FITS_HOME=/home/travis/build/Det-Kongelige-Bibliotek/valhal/fits-0.6.2/fits.sh
