language: ruby
services:
  - rabbitmq
notifications:
  email: true
rvm:
  - "1.9.3"
install:
  - bundle install --deployment
  - rake jetty:clean
  - rake hydra:jetty:config
before_script:
  - rake db:migrate db:seed db:test:prepare
  - rake jetty:start
after_script:
  - rake jetty:stop
