development:
  activemq:
    broker_uri: "failover:(tcp://localhost:61613?keepAlive=true)"
    preservation_destination: "/topic/event"

test:
  activemq:
    broker_uri: "failover:(tcp://localhost:61613?keepAlive=true)"
    preservation_destination: "/topic/event"

production:
  activemq:
    broker_uri: "failover:(tcp://localhost:61613?keepAlive=true)"
    preservation_destination: "/topic/event"
