# For authority metadata units. Configures which relations each type can have
authority_metadata_unit:
  concept:
    isTopicOf
  event:
    isTopicOf
  physicalThing:
    isTopicOf
  place:
    isTopicOf
    isOriginOf
    isDestinationOf
  agent/person:
    isAddresseeOf
    isAuthorOf
    isAgentOf
    isContributorOf
    isCreatorOf
    isOwnerOf
    isPatronOf
    isPerformerOf
    isPhotographerOf
    isPrinterOf
    isPublisherOf
    isScribeOf
    isTranslatorOf
    isDigitizerOf
    isTopicOf
  agent/organization:
    isAddresseeOf
    isAuthorOf
    isAgentOf
    isContributorOf
    isCreatorOf
    isOwnerOf
    isPatronOf
    isPerformerOf
    isPhotographerOf
    isPrinterOf
    isPublisherOf
    isScribeOf
    isTranslatorOf
    isDigitizerOf
    isTopicOf

# For Work and Instance, just which relations each can have.
work:
  hasTopic
  hasOrigin
  hasDestination
  hasAddressee
  hasAuthor
  hasContributor
  hasCreator
  hasOwner
  hasPatron
  hasPerformer
  hasPhotographer
  hasTranslator
instance:
  hasTopic
  hasOrigin
  hasContributor
  hasOwner
  hasPatron
  hasPrinter
  hasPublisher
  hasScribe
  hasDigitizer

