development:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-dev-queue"
    response: "preservation-response-dev-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "dissemination-bifrost-books-dev-queue"
  digitisation:
    source: "digitisation-dev-queue"
    polling_interval_in_minutes: 1
  workflow:
    destination: "workflow-dev-queue"

test:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-test-queue"
    response: "preservation-response-test-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "dissemination-bifrost-books-test-queue"
  digitisation:
      source: "digitisation-test-queue"
      polling_interval_in_minutes: 1
  workflow:
    destination: "workflow-test-queue"

production:
  mq_uri: "amqp://sifd-staging-03:5672"
  preservation:
    destination: "preservation-prod-queue"
    response: "preservation-response-prod-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "bifrost-ingest-prod-queue"
  digitisation:
      source: "digitisation-prod-queue"
      polling_interval_in_minutes: 1
  workflow:
    destination: "workflow-prod-queue"
