development:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-dev-queue"
    response: "preservation-response-dev-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "dissemination-bifrost_books-dev-queue"
  digitisation:
    source: "digitisation-dev-queue"
    polling_interval_in_minutes: 1

test:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-test-queue"
    response: "preservation-response-test-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "dissemination-bifrost_books-test-queue"
  digitisation:
      source: "digitisation-test-queue"
      polling_interval_in_minutes: 1

production:
  mq_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-prod-queue"
    response: "preservation-response-prod-queue"
    polling_interval_in_minutes: 1
  dissemination:
    bifrost_books: "dissemination-bifrost_books-prod-queue"
  digitisation:
      source: "digitisation-prod-queue"
      polling_interval_in_minutes: 1
