development:
  broker_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-dev-queue"
  dissemination:
    destination: "dissemination-dev-queue"

test:
  broker_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-test-queue"
  dissemination:
    destination: "dissemination-test-queue"

production:
  broker_uri: "amqp://localhost:5672"
  preservation:
    destination: "preservation-prod-queue"
  dissemination:
    destination: "dissemination-prod-queue"
