# The default namespace maps to the default namespace for generating rels_ext from solr
:default_namespace: info:fedora/fedora-system:def/relations-external#

# namespace mappings--- 
# you can add specific mappings for your institution by providing the following:
#   namespace_uri:
#     :relationship_symbol: relationship_identifier
# 
# For example, if you have the following element in your rels_ext:
#  
#  <oai:itemID>oai:example.edu:changeme:500</oai:itemID>
# 
# With the last two lines of this basic_files uncommented, the relationships hash of your object will include:
#   :oai_item_id => ["info:fedora/oai:example.edu:changeme:500"]
#
:predicate_mapping:
  http://www.kb.dk/:
    # A book or a work can concern an agent
    :concerning: isDescriptionOf
    # A work can have representations
    :has_representation: hasSubset
    # An agent can be concerned by a work
    :is_concerned_by: hasDescription
    # A representation is representing either a book or a work.
    :is_representation_of: isSubsetOf

    ##################################
    # Relations for authority metadata
    ##################################
    # Topic relationship from work/instance perspective
    :has_topic: hasTopic
    # Topic relationship from metadata perspective
    :is_topic_of: isTopicOf
    # Origin relationship from work/instance perspective
    :has_origin: hasOrigin
    # Origin relationship from metadata perspective
    :is_origin_of: isOriginOf
    # Created relationship from work/instance perspective
    :has_created: hasCreated
    # Created relationship from metadata perspective
    :is_created_of: isCreatedOf

    ### AGENTS ONLY ###
    # Addressee relationship from work/instance perspective
    :has_addressee: hasAddressee
    # Addressee relationship from metadata perspective
    :is_addressee_of: isAddresseeOf
    # Agent relationship from work/instance perspective
    :has_agent: hasAgent
    # Agent relationship from metadata perspective
    :is_agent_of: isAgentOf
    # Contributor relationship from work/instance perspective
    :has_contributor: hasContributor
    # Contributor relationship from metadata perspective
    :is_contributor_of: isContributorOf
    # Creator relationship from work/instance perspective
    :has_creator: hasCreator
    # Creator relationship from metadata perspective
    :is_creator_of: isCreatorOf
    # Owner relationship from work/instance perspective
    :has_owner: hasOwner
    # Owner relationship from metadata perspective
    :is_owner_of: isOwnerOf
    # Patron relationship from work/instance perspective
    :has_patron: hasPatron
    # Patron relationship from metadata perspective
    :is_patron_of: isPatronOf
    # Performer relationship from work/instance perspective
    :has_performer: hasPerformer
    # Performer relationship from metadata perspective
    :is_performer_of: isPerformerOf
    # Photographer relationship from work/instance perspective
    :has_photographer: hasPhotographer
    # Photographer relationship from metadata perspective
    :is_photographer_of: isPhotographerOf
    # Printer relationship from work/instance perspective
    :has_printer: hasPrinter
    # Printer relationship from metadata perspective
    :is_printer_of: isPrinterOf
    # Publisher relationship from work/instance perspective
    :has_publisher: hasPublisher
    # Publisher relationship from metadata perspective
    :is_publisher_of: isPublisherOf
    # Scribe relationship from work/instance perspective
    :has_scribe: hasScribe
    # Scribe relationship from metadata perspective
    :is_scribe_of: isScribeOf
    # Translator relationship from work/instance perspective
    :has_translator: hasTranslator
    # Translator relationship from metadata perspective
    :is_translator_of: isTranslatorOf
    # Digitizer relationship from work/instance perspective
    :has_digitizer: hasDigitizer
    # Digitizer relationship from metadata perspective
    :is_digitizer_of: isDigitizerOf

  info:fedora/fedora-system:def/relations-external#:
    :conforms_to: conformsTo
    :has_annotation: hasAnnotation
    :has_collection_member: hasCollectionMember
    :has_constituent: hasConstituent
    :has_dependent: hasDependent
    :has_derivation: hasDerivation
    :has_description: hasDescription
    :has_equivalent: hasEquivalent
    :has_metadata: hasMetadata
    :has_member: hasMember
    :has_model: hasModel
    :has_part: hasPart
    :has_subset: hasSubset
    :has_topic: hasTopic
    :has_agent: hasAgent
    :is_annotation_of: isAnnotationOf
    :is_constituent_of: isConstituentOf
    :is_dependent_of: isDependentOf
    :is_derivation_of: isDerivationOf
    :is_description_of: isDescriptionOf
    :is_member_of: isMemberOf
    :is_member_of_collection: isMemberOfCollection
    :is_metadata_for: isMetadataFor
    :is_part_of: isPartOf
    :is_subset_of: isSubsetOf
    :is_topic_of: isTopicOf
    :is_agent_of: isAgentOf
  info:fedora/fedora-system:def/model#:
    :is_contractor_of: isContractorOf
    :is_deployment_of: isDeploymentOf
    :has_service: hasService
    :has_model: hasModel
  http://www.openarchives.org/OAI/2.0/:
    :oai_item_id: itemID
  http://projecthydra.org/ns/relations#:
    :is_governed_by: isGovernedBy
