development:
  preservation_profile:
    storage:
      bit_safety: "Minimum Bitsafety (Not in Bitrepository: 1 local copy, no integrity checks)"
      confidentiality: "Low confidentiality (Everyone with access to Valhal)."
      yggdrasil: 'false'
    simple:
      bit_safety: "Medium Bitsafety (Bitrepository with 3 x copies: 2 full and one checksum, and regularly integrity checks)"
      confidentiality: "Medium confidentiality (no access through bitrepository, and limited access to basic_files at pillars/backends)"
      yggdrasil: 'true'
    eternity:
      bit_safety: "Maximum Bitsafety (15 x copies: 10 in Bitrepository with daily integrity checks, 5 on open sites on the Internet, 1 on other the Moon and 1 in another galaxy)"
      confidentiality: "Minimum confidentiality (public accessible through the Internet)"
      yggdrasil: 'true'

test:
  preservation_profile:
    storage:
      bit_safety: "Minimum Bitsafety (Not in Bitrepository: 1 local copy, no integrity checks)"
      confidentiality: "Low confidentiality (Everyone with access to Valhal)."
      yggdrasil: 'false'
    simple:
      bit_safety: "Medium Bitsafety (Bitrepository with 3 x copies: 2 full and one checksum, and regularly integrity checks)"
      confidentiality: "Medium confidentiality (no access through bitrepository, and limited access to basic_files at pillars/backends)"
      yggdrasil: 'true'
    eternity:
      bit_safety: "Maximum Bitsafety (15 x copies: 10 in Bitrepository with daily integrity checks, 5 on open sites on the Internet, 1 on other the Moon and 1 in another galaxy)"
      confidentiality: "Minimum confidentiality (public accessible through the Internet)"
      yggdrasil: 'true'

production:
  preservation_profile:
    storage:
      bit_safety: "Minimum Bitsafety (Not in Bitrepository: 1 local copy, no integrity checks)"
      confidentiality: "Low confidentiality (Everyone with access to Valhal)."
      yggdrasil: 'false'
    simple:
      bit_safety: "Medium Bitsafety (Bitrepository with 3 x copies: 2 full and one checksum, and regularly integrity checks)"
      confidentiality: "Medium confidentiality (no access through bitrepository, and limited access to basic_files at pillars/backends)"
      yggdrasil: 'true'
    eternity:
      bit_safety: "Maximum Bitsafety (15 x copies: 10 in Bitrepository with daily integrity checks, 5 on open sites on the Internet, 1 on other the Moon and 1 in another galaxy)"
      confidentiality: "Minimum confidentiality (public accessible through the Internet)"
      yggdrasil: 'true'
